name: è‡ªåŠ¨å‹ç¼©å›¾ç‰‡å¹¶åˆå¹¶æ‹‰å–è¯·æ±‚

on:
  push:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
  pull_request:
    types: [opened, synchronize]

jobs:
  compress-image:
    name: å‹ç¼©å›¾ç‰‡
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.MYGITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: '60'
          jpegProgressive: false
          pngQuality: '60'
          webpQuality: '60'
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[ci skip] ğŸ›  å‹ç¼©å›¾ç‰‡'
          branch-suffix: timestamp
          commit-message: 'ğŸ›  å‹ç¼©å›¾ç‰‡'
          body: ${{ steps.calibre.outputs.markdown }}

  merge-pr:
    name: è‡ªåŠ¨åˆå¹¶æ‹‰å–è¯·æ±‚
    runs-on: ubuntu-latest
    needs: [compress-image]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge pull request
        uses: peter-evans/pull-request-merge@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
